@host = http://localhost:5000

### Proxy - Products
GET {{host}}/api/products
Accept: application/json

### Proxy - Customers
GET {{host}}/api/customers
Accept: application/json

### Proxy - Orders
GET {{host}}/api/orders
Accept: application/json
